

services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home

  frontend:
    build:
      context: ./src/monitoring-dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
