

services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./src/monitoring-dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DBT_CH_HOST
      - DBT_CH_PORT
      - DBT_CH_USER
      - DBT_CH_PASSWORD
      - DBT_CH_DB_SILVER
    extra_hosts:
      - "host.docker.internal:host-gateway"
