clickhouse_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('DBT_CH_HOST') }}"
      port: "{{ env_var('DBT_CH_PORT') | int }}"
      user: "{{ env_var('DBT_CH_USER') }}"
      password: "{{ env_var('DBT_CH_PASSWORD') }}"
      database: "{{ env_var('DBT_CH_DB') }}"
      secure: False
      verify: False
