[sources.filesystem.credentials]
aws_access_key_id = "Ynov"
aws_secret_access_key = "Ynov2026*"
endpoint_url = "https://minio-gitmonitor.46.224.33.190.sslip.io"

[sources.filesystem]
bucket_url = "s3://bronze/dependencies"

[destination.postgres.credentials]
database = "postgres"
password = "Ynov2026*"
username = "postgres"
host = "46.224.33.190"
port = 5434
